blank_issues_enabled: false
contact_links:
  - name: 🎮 AzerothCore Community Discord
    url: https://discord.gg/gkt4y2x
    about: Join the AzerothCore Discord for community support and discussions
  - name: 📚 Documentation
    url: https://github.com/your-org/azerothcore-builder#readme
    about: Check our comprehensive documentation for guides and tutorials
  - name: 💬 GitHub Discussions
    url: https://github.com/your-org/azerothcore-builder/discussions
    about: Ask questions and discuss ideas with the community